version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}

  # User Service (Classic Akka Actors)
  user-service-classic:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - notification-service-classic

  # Notification Service (Classic Akka Actors)
  notification-service-classic:
    build: ./notification-service
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector

  # User Service (Typed Akka Actors)
  user-service-typed:
    build: ./user-service-typed
    ports:
      - "8082:8080"
    depends_on:
      - otel-collector
      - notification-service-typed

  # Notification Service (Typed Akka Actors)
  notification-service-typed:
    build: ./notification-service-typed
    ports:
      - "8083:8081"
    depends_on:
      - otel-collector

networks:
  default:
    name: scala-akka-otel